# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_gap_analyzer', '0002_jobdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdata',
            old_name='jobReuirments',
            new_name='jobRequirments',
        ),
    ]
